api_version = "2024-07"

[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:title"
handle = "loyal-customers-template"
type = "ui_extension"

description = "t:description"
[[extensions.targeting]]
module = "./src/CustomerSegmentTemplate.tsx"
# The target used here must match the target used in the module file (./src/CustomerSegmentTemplate.tsx)
target = "admin.customers.segmentation-templates.render"


# Valid extension points:

# - admin.customers.segmentation-templates.render
