[[extensions]]
name = "t:collection_one_name"
handle = "wishlist-management"
type = "editor_extension_collection"

# Add the handles of the extensions you want in this collection here
includes = ["customer-account-wishlist", "customer-wishlist-entry"]

# You can also add extensions to the collection this way
#[[extensions.include]]
#handle=""

# A second editor extension collection added in the same extension toml config
# [[extensions]]
# name = "t:collection_two_name"
# type = "editor_extension_collection"
# handle = "wishlist-management"
# includes=[]
