[[extensions]]
name = "Auction Bid Placed"
handle = "auction-bid-placed"
type = "flow_trigger"

description = "Trigger for auction bids."

[settings]

[[settings.fields]]
type = "customer_reference"

[[settings.fields]]
type = "number_decimal"
key = "Amount"
